{ den, lib, ... }:
{
  den.aspects.services.provides.media =
    let
      group-name = "media";
      services = [
        "jelly"
        "qbit"
        "radarr"
        "sonarr"
        "bazarr"
        "prowlarr"
        "flaresolverr"
      ];
      containers = lib.genAttrs services (service: "${group-name}-${service}");

      address = "127.0.0.1";
      port = {
        jelly = 8096;
        qbit = 8112;
        radarr = 7878;
        sonarr = 8989;
        bazarr = 6767;
        prowlarr = 9696;
      };
    in
    {
      description = "Media Server";

      includes = map (service: den.aspects.services._.media._.${service}) services;

      nixos =
        {
          config,
          pkgs,
          lib,
          ...
        }:
        let
          root-target = "podman-compose-${group-name}-root";
          network-service = "podman-network-${group-name}";
          systemd-services = builtins.listToAttrs (
            map (container: {
              name = config.virtualisation.oci-containers.containers.${container}.serviceName;
              value = {
                serviceConfig = {
                  Restart = lib.mkOverride 90 "always";
                };
                after = [
                  "${network-service}.service"
                ];
                requires = [
                  "${network-service}.service"
                ];
                partOf = [
                  "${root-target}.target"
                ];
                wantedBy = [
                  "${root-target}.target"
                ];
              };
            }) (builtins.attrValues containers)
          );
          container-network = builtins.listToAttrs (
            map (container: {
              name = container;
              value.extraOptions = [ "--network=${group-name}" ];
            }) (builtins.attrValues containers)
          );
        in
        {
          systemd.services = systemd-services // {
            ${network-service} = {
              path = [ pkgs.podman ];
              serviceConfig = {
                Type = "oneshot";
                RemainAfterExit = true;
                ExecStop = "podman network rm -f ${group-name}";
              };
              script = "podman network inspect ${group-name} || podman network create ${group-name}";
              partOf = [ "${root-target}.target" ];
              wantedBy = [ "${root-target}.target" ];
            };
          };
          virtualisation.oci-containers.containers = container-network;

          # Root service
          # When started, this will automatically create all resources and start
          # the containers. When stopped, this will teardown all resources.
          systemd.targets.${root-target} = {
            unitConfig = {
              Description = "Root target generated by compose2nix.";
            };
            wantedBy = [ "multi-user.target" ];
          };
        };

      provides = {
        jelly = {
          description = "Jellyfin";
          nixos.virtualisation.oci-containers.containers.${containers.jelly} = {
            image = "ghcr.io/hotio/jellyfin:latest";
            environment = {
              "NVIDIA_DRIVER_CAPABILITIES" = "all";
              "NVIDIA_VISIBLE_DEVICES" = "all";
              "PGID" = "100";
              "PUID" = "1000";
              "TZ" = "America/Sao_Paulo";
            };
            volumes = [
              "/etc/localtime:/etc/localtime:ro"
              "/vol/drive/containers/media/appdata/jellyfin:/config:rw"
              "/vol/drive/containers/media/data/media:/data/media:rw"
            ];
            ports = [ "${address}:${toString port.jelly}:8096/tcp" ];
            labels."io.containers.autoupdate" = "registry";
            log-driver = "journald";
            extraOptions = [
              "--device=nvidia.com/gpu=all"
              "--network-alias=jellyfin"
              "--security-opt=label=disable"
            ];
          };
        };
        qbit = {
          description = "qBittorrent";
          nixos.virtualisation.oci-containers.containers.${containers.qbit} = {
            image = "ghcr.io/hotio/qbittorrent:latest";
            environment = {
              "PGID" = "100";
              "PUID" = "1000";
              "TZ" = "America/Sao_Paulo";
              "WEBUI_PORTS" = "8112/tcp,8112/udp";
            };
            volumes = [
              "/etc/localtime:/etc/localtime:ro"
              "/vol/drive/containers/media/appdata/qbittorrent:/config:rw"
              "/vol/drive/containers/media/data/torrents:/data/torrents:rw"
            ];
            ports = [ "${address}:${toString port.qbit}:8112/tcp" ];
            labels."io.containers.autoupdate" = "registry";
            log-driver = "journald";
            extraOptions = [ "--network-alias=qbittorrent" ];
          };
        };
        radarr = {
          description = "Radarr";
          nixos.virtualisation.oci-containers.containers.${containers.radarr} = {
            image = "ghcr.io/hotio/radarr:latest";
            environment = {
              "PGID" = "100";
              "PUID" = "1000";
              "TZ" = "America/Sao_Paulo";
            };
            volumes = [
              "/etc/localtime:/etc/localtime:ro"
              "/vol/drive/containers/media/appdata/radarr:/config:rw"
              "/vol/drive/containers/media/data:/data:rw"
            ];
            ports = [ "${address}:${toString port.radarr}:7878/tcp" ];
            labels."io.containers.autoupdate" = "registry";
            log-driver = "journald";
            extraOptions = [ "--network-alias=radarr" ];
          };
        };
        sonarr = {
          description = "Sonarr";
          nixos.virtualisation.oci-containers.containers.${containers.sonarr} = {
            image = "ghcr.io/hotio/sonarr:latest";
            environment = {
              "PGID" = "100";
              "PUID" = "1000";
              "TZ" = "America/Sao_Paulo";
            };
            volumes = [
              "/etc/localtime:/etc/localtime:ro"
              "/vol/drive/containers/media/appdata/sonarr:/config:rw"
              "/vol/drive/containers/media/data:/data:rw"
            ];
            ports = [ "${address}:${toString port.sonarr}:8989/tcp" ];
            labels."io.containers.autoupdate" = "registry";
            log-driver = "journald";
            extraOptions = [ "--network-alias=sonarr" ];
          };
        };
        bazarr = {
          description = "Bazarr";
          nixos.virtualisation.oci-containers.containers.${containers.bazarr} = {
            image = "ghcr.io/hotio/bazarr:latest";
            environment = {
              "PGID" = "100";
              "PUID" = "1000";
              "TZ" = "America/Sao_Paulo";
            };
            volumes = [
              "/etc/localtime:/etc/localtime:ro"
              "/vol/drive/containers/media/appdata/bazarr:/config:rw"
              "/vol/drive/containers/media/data/media:/data/media:rw"
            ];
            ports = [ "${address}:${toString port.bazarr}:6767/tcp" ];
            labels."io.containers.autoupdate" = "registry";
            log-driver = "journald";
            extraOptions = [ "--network-alias=bazarr" ];
          };
        };
        prowlarr = {
          description = "Prowlarr";
          nixos.virtualisation.oci-containers.containers.${containers.prowlarr} = {
            image = "ghcr.io/hotio/prowlarr:latest";
            environment = {
              "PGID" = "100";
              "PUID" = "1000";
              "TZ" = "America/Sao_Paulo";
            };
            volumes = [
              "/etc/localtime:/etc/localtime:ro"
              "/vol/drive/containers/media/appdata/prowlarr:/config:rw"
            ];
            ports = [ "${address}:${toString port.prowlarr}:9696/tcp" ];
            labels."io.containers.autoupdate" = "registry";
            log-driver = "journald";
            extraOptions = [ "--network-alias=prowlarr" ];
          };
        };
        flaresolverr = {
          description = "Flaresolverr";
          nixos.virtualisation.oci-containers.containers.${containers.flaresolverr} = {
            image = "ghcr.io/flaresolverr/flaresolverr:latest";
            environment."TZ" = "America/Sao_Paulo";
            volumes = [ "/etc/localtime:/etc/localtime:ro" ];
            labels."io.containers.autoupdate" = "registry";
            log-driver = "journald";
            extraOptions = [ "--network-alias=flaresolverr" ];
          };
        };

        setupCaddy =
          {
            jelly,
            qbit,
            radarr,
            sonarr,
            bazarr,
            prowlarr,
          }:
          {
            description = "Setup Caddy reverse proxy";
            includes = [
              (den.aspects.services._.caddy._.addVirtualHost jelly ''
                encode zstd gzip
                header / {
                  Strict-Transport-Security "max-age=31536000;"
                  X-XSS-Protection "0"
                  X-Frame-Options "SAMEORIGIN"
                  X-Robots-Tag "noindex, nofollow"
                  X-Content-Type-Options "nosniff"
                }
                reverse_proxy ${address}:${toString port.jelly}
              '')
              (den.aspects.services._.caddy._.addVirtualHost qbit ''
                encode zstd gzip
                header / {
                  Strict-Transport-Security "max-age=31536000;"
                  X-XSS-Protection "0"
                  X-Frame-Options "SAMEORIGIN"
                  X-Robots-Tag "noindex, nofollow"
                  X-Content-Type-Options "nosniff"
                }
                reverse_proxy ${address}:${toString port.qbit}
              '')
              (den.aspects.services._.caddy._.addVirtualHost radarr ''
                encode zstd gzip
                header / {
                  Strict-Transport-Security "max-age=31536000;"
                  X-XSS-Protection "0"
                  X-Frame-Options "SAMEORIGIN"
                  X-Robots-Tag "noindex, nofollow"
                  X-Content-Type-Options "nosniff"
                }
                reverse_proxy ${address}:${toString port.radarr}
              '')
              (den.aspects.services._.caddy._.addVirtualHost sonarr ''
                encode zstd gzip
                header / {
                  Strict-Transport-Security "max-age=31536000;"
                  X-XSS-Protection "0"
                  X-Frame-Options "SAMEORIGIN"
                  X-Robots-Tag "noindex, nofollow"
                  X-Content-Type-Options "nosniff"
                }
                reverse_proxy ${address}:${toString port.sonarr}
              '')
              (den.aspects.services._.caddy._.addVirtualHost bazarr ''
                encode zstd gzip
                header / {
                  Strict-Transport-Security "max-age=31536000;"
                  X-XSS-Protection "0"
                  X-Frame-Options "SAMEORIGIN"
                  X-Robots-Tag "noindex, nofollow"
                  X-Content-Type-Options "nosniff"
                }
                reverse_proxy ${address}:${toString port.bazarr}
              '')
              (den.aspects.services._.caddy._.addVirtualHost prowlarr ''
                encode zstd gzip
                header / {
                  Strict-Transport-Security "max-age=31536000;"
                  X-XSS-Protection "0"
                  X-Frame-Options "SAMEORIGIN"
                  X-Robots-Tag "noindex, nofollow"
                  X-Content-Type-Options "nosniff"
                }
                reverse_proxy ${address}:${toString port.prowlarr}
              '')
            ];
          };
        setupCloudflareTunnel = id: domain: {
          description = "Setup Cloudflare Tunnel";
          includes = [
            (den.aspects.services._.cloudflared._.addIngress {
              inherit id;
              ingress.${domain}.service = "http://${address}:${toString port.jelly}";
            })
          ];
        };
      };
    };
}
