{ pkgs, ... }:

{
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      alsa-lib
      at-spi2-atk
      at-spi2-core
      libxcrypt
      atk
      cairo
      cups
      curl
      dbus
      expat
      fontconfig
      freetype
      fuse
      fuse3
      gdk-pixbuf
      glib
      glibc
      gtk3
      harfbuzz
      icu
      libcap
      libGL
      libva
      libappindicator-gtk3
      libdrm
      libglvnd
      libnotify
      libpulseaudio
      libunwind
      libusb1
      libuuid
      libxcrypt
      libxkbcommon
      libxml2
      libgbm
      libudev0-shim
      icu
      udev
      mesa
      nspr
      nss
      openssl
      pango
      pipewire
      stdenv.cc.cc
      systemd
      vulkan-loader
      xorg.libX11
      xorg.libXScrnSaver
      xorg.libXcomposite
      xorg.libXcursor
      xorg.libXdamage
      xorg.libXext
      xorg.libXfixes
      xorg.libXi
      xorg.libXrandr
      xorg.libXrender
      xorg.libXtst
      xorg.libxcb
      xorg.libxkbfile
      xorg.libxshmfence
      zlib
      vlc
      stdenv.cc.cc.lib
    ];
  };
}
