name: "populate cache"
on:
  workflow_call:
env:
  CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
jobs:
  cache:
    runs-on: nixos-unstable
    steps:
      - name: Install node
        run: nix profile add nixpkgs#nodejs_latest
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6
      - name: Install needed packages
        run: nix profile add github:juspay/omnix github:juspay/cachix-push nixpkgs#cachix
      - name: Setup cachix
        run: |
          CACHES=(
            'henriquekh'
            'nix-community'
            'hyprland'
            'niri'
            'nix-on-droid'
          )
          for cache in ${CACHES[@]}; do
            cachix use $cache
          done
      - name: Build output
        run: om ci run --results=/om.json
      - name: Push to cache
        run: cachix-push-om-outputs -c henriquekh --subflake ROOT --prefix "$(git rev-parse --short HEAD)" < /om.json
