name: "check flake"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check:
    runs-on: nixos-unstable
    steps:
      - name: Install node
        run: nix profile add nixpkgs#nodejs_latest
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6
      - name: Check code
        run: nix fmt -- --ci
      - name: Check flake
        run: nix flake check --all-systems
  cache:
    needs: check
    uses: ./.forgejo/workflows/cache.yml
    secrets: inherit
