{ pkgs, lib, config, ... }:

{
  sops.secrets.searxng_env = {
    sopsFile = ./secrets/searxng.env;
    format = "dotenv";
  };

  # Containers
  virtualisation.oci-containers.containers."searxng" = {
    image = "docker.io/searxng/searxng:latest";
    volumes = [
      "/vol/drive/containers/searxng/searxng:/etc/searxng:rw"
      "searxng_searxng-data:/var/cache/searxng:rw"
    ];
    environmentFiles = [ config.sops.secrets.searxng_env.path ];
    ports = [
      "5947:8080/tcp"
    ];
    labels = {
      "io.containers.autoupdate" = "registry";
    };
    dependsOn = [
      "searxng-valkey"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=searxng"
      "--network=searxng_searxng"
    ];
  };
  systemd.services."podman-searxng" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-searxng_searxng.service"
      "podman-volume-searxng_searxng-data.service"
    ];
    requires = [
      "podman-network-searxng_searxng.service"
      "podman-volume-searxng_searxng-data.service"
    ];
    partOf = [
      "podman-compose-searxng-root.target"
    ];
    upheldBy = [
      "podman-network-searxng_searxng.service"
      "podman-searxng-valkey.service"
      "podman-volume-searxng_searxng-data.service"
    ];
    wantedBy = [
      "podman-compose-searxng-root.target"
    ];
  };
  virtualisation.oci-containers.containers."searxng-valkey" = {
    image = "docker.io/valkey/valkey:8-alpine";
    volumes = [
      "searxng_valkey-data:/data:rw"
    ];
    cmd = [ "valkey-server" "--save" "30" "1" "--loglevel" "warning" ];
    labels = {
      "io.containers.autoupdate" = "registry";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=valkey"
      "--network=searxng_searxng"
    ];
  };
  systemd.services."podman-searxng-valkey" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-searxng_searxng.service"
      "podman-volume-searxng_valkey-data.service"
    ];
    requires = [
      "podman-network-searxng_searxng.service"
      "podman-volume-searxng_valkey-data.service"
    ];
    partOf = [
      "podman-compose-searxng-root.target"
    ];
    upheldBy = [
      "podman-network-searxng_searxng.service"
      "podman-volume-searxng_valkey-data.service"
    ];
    wantedBy = [
      "podman-compose-searxng-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-searxng_searxng" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f searxng_searxng";
    };
    script = ''
      podman network inspect searxng_searxng || podman network create searxng_searxng
    '';
    partOf = [ "podman-compose-searxng-root.target" ];
    wantedBy = [ "podman-compose-searxng-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-searxng_searxng-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect searxng_searxng-data || podman volume create searxng_searxng-data
    '';
    partOf = [ "podman-compose-searxng-root.target" ];
    wantedBy = [ "podman-compose-searxng-root.target" ];
  };
  systemd.services."podman-volume-searxng_valkey-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect searxng_valkey-data || podman volume create searxng_valkey-data
    '';
    partOf = [ "podman-compose-searxng-root.target" ];
    wantedBy = [ "podman-compose-searxng-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-searxng-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
